### ISSUE TITLE
Updating the program

### ISSUE THREAD

**Issue by ghost** [ZoserLock/keyboard-unchatter#1]
Hey, I just wanted to say that I absolutely LOVE your program. It's open source and helped me eliminate chattering. Will you update it some more or is it finalized completely (I see last update was pretty far back in December)

**Comment by ZoserLock** [comment]
Hi!, sorry about the really late response.

I did not continue developing this as I bought a new keyboard without the shattering problem. But since I just see this message maybe I will try to finish some thing that are half done.

Thanks!
